repos:
  # Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [--fix]
  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
